###
GET http://localhost:1337/

###
POST http://localhost:1337/api/v1/echo
Content-Type: application/json

{
  "message": "Hello World!",
  "delay": 1000
}

###
GET http://localhost:1337/api/v1/posts
